#       Copyright 2017-2019 IBM Corp All Rights Reserved

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

{{- if .Values.trader.enabled }}
#Deploy the pod
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-trader
  labels:
    app: {{ .Release.Name }}-stock-trader
  annotations: { 
    prism.subkind: Liberty
  }
spec:
  replicas: {{ .Values.global.replicas }}
  template:
    metadata:
      labels:
        app: trader
{{- if .Values.global.monitoring }}
      annotations: { 
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9080'
        prometheus.io/scheme: http        
      }
{{- end }}
    spec:
      containers:
      - name: trader
        image: "{{ .Values.trader.image.repository }}:{{ .Values.trader.image.tag }}"
        env:
          - name: JWT_AUDIENCE
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config 
                key: jwt.audience
          - name: JWT_ISSUER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: jwt.issuer
          - name: PORTFOLIO_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: portfolio.url
                optional: true
        ports:
          - containerPort: 9080
          - containerPort: 9443
        imagePullPolicy: Always
{{- if .Values.global.healthCheck }}
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 30
          periodSeconds: 6
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 60
          periodSeconds: 6
{{- end }}
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 128Mi
      nodeSelector:
        beta.kubernetes.io/arch: amd64
---
#Deploy the autoscaler
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-trader-hpa
  labels:
    app: stock-trader
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-trader
  maxReplicas: {{ .Values.global.replicas }}
  minReplicas: 1
  targetCPUUtilizationPercentage: 60
---
#Deploy the service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-trader-service
  labels:
    app: trader
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: trader
---
#Configure the ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-trader-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    #ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/secure-backends: "true"
    #ingress.kubernetes.io/app-root: "/trader"
    ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: stocktrader.ibm.com
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-trader-service
          servicePort: 9443
  tls:
  - hosts:
    - stocktrader.ibm.com
{{- end }}
